issuer_response_codes:
  "00": "ODMOWA - wystąpił błąd. Transakcja została odrzucona ze względu na brak odpowiedzi z banku, blokadę konta Sprzedawcy, użycie nieobsługiwanego typu karty lub nieprawidłowe dane karty. Prosimy spróbować ponownie później lub skontaktować się z Działem Wsparcia Technicznego Espago."
  "1A": "Dla kart Visa: ta płatność wymaga dokonania silnego uwierzytelnienia (SCA)."
  "65": "Mastercard: ODMOWA – ta płatność wymaga dokonania silnego uwierzytelnienia (SCA).<br><br>VISA: ODMOWA – przekroczony dzienny limit liczby transakcji dla tej karty. Dokonaj zmiany ustawień dziennych limitów lub spróbuj ponownie później."
  "01": &01_code "ODMOWA - problem z autoryzacją. Niezbędny kontakt z bankiem."
  "02": *01_code
  "03": "ODMOWA - problem z autoryzacją.UWAGA: Nie wolno powtarzać obciążeń dla tej karty."
  "04": "ODMOWA - karta zastrzeżona. Skontaktuj się z Twoim bankiem w celu wyjaśnienia przyczyny problemu. UWAGA: Nie wolno powtarzać obciążeń dla tej karty."
  "05": "Płatność została odrzucona przez bank bez podania szczególnej przyczyny. Prawdopodobnie płatności typu MOTO/eCommerce/subskrypcyjne nieaktywne lub niewspierane. Potrzebny kontakt klienta z bankiem w celu wyjaśnienia.<br>ODMOWA – bank odrzucił transakcję ze względu na ustawienia zabezpieczeń (np. karta nie obsługuje płatności cyklicznych/bez kodu CVV) albo blokadę środków lub karta nie obsługuje płatności internetowych/MOTO. Sprawdź ustawienia karty lub użyj innej karty."
  "07": "ODMOWA - karta zastrzeżona.UWAGA: Nie wolno powtarzać obciążeń dla tej karty."
  "12": "ODMOWA - transakcja niedostępna dla tej karty. Skontaktuj się z Twoim bankiem w celu wyjaśnienia przyczyny problemu*UWAGA: Nie wolno powtarzać obciążeń dla tej karty.*"
  "13": "ODMOWA – Sprawdź, czy dla Twojej karty dostępna jest usługa płatności internetowych lub MOTO, zweryfikuj ustawienia limitów dla takich transakcji lub skontaktuj się z Twoim bankiem (wystawcą karty) w celu wyjaśnienia przyczyny odmowy."
  "14": "ODMOWA - podano nieprawidłowy numer karty. Należy użyć innej karty. UWAGA: Nie wolno powtarzać obciążeń dla tej karty."
  "15": "ODMOWA - podano nieprawidłowy numer karty. Należy użyć innej karty. UWAGA: Nie wolno powtarzać obciążeń dla tej karty."
  "30": "ODMOWA - skontaktuj się z Twoim bankiem w celu wyjaśnienia przyczyny problemu"
  "41": "ODMOWA - karta oznaczona jako zgubiona – skontaktuj się z Twoim bankiem w celu wyjaśnienia przyczyny problemu. UWAGA: Nie wolno powtarzać obciążeń dla tej karty."
  "43": "ODMOWA - karta oznaczona jako skradziona – skontaktuj się z Twoim bankiem w celu wyjaśnienia przyczyny problemu. UWAGA: Nie wolno powtarzać obciążeń dla tej karty."
  "46": "ODMOWA - Płatność odrzucona przez bank – proszę użyć innej karty. UWAGA: Nie wolno powtarzać obciążeń dla tej karty."
  "51": "ODMOWA - niewystarczające środki na koncie lub przekroczenie limitu. Zweryfikuj stan swojego konta i spróbuj ponownie."
  "54": "ODMOWA - karta utraciła ważność.  Użyj innej karty.UWAGA: Nie wolno powtarzać obciążeń dla tej karty."
  "57": "ODMOWA – bank odrzucił transakcję ponieważ użyta karta nie może zostać użyta to tego typu transakcji (internetowe, MOTO lub cykliczne). Sprawdź ustawienia karty lub użyj innej karty.UWAGA: Nie wolno powtarzać obciążeń dla tej karty."
  "59": "ODMOWA - skontaktuj się z Twoim bankiem w celu wyjaśnienia przyczyny problemu"
  "61": "ODMOWA - przekroczenie limitu kwoty transakcji. Skontaktuj się z bankiem w celu zmiany limitu lub użyj innej karty."
  "62": "ODMOWA – użycie karty zostało ograniczone, np. ze względu na ograniczenie (embargo) nałożone na kraj wydawcy (banku). Skontaktuj się z bankiem w celu wyjaśnienia szczegółowej przyczyny problemu.UWAGA: Nie wolno powtarzać obciążeń dla tej karty."
  "75": "ODMOWA – przekroczony limit błędnych prób podania kodu CVV/CVC/PIN. Zweryfikuj poprawność kodu zabezpieczającego na swojej karcie."
  "78": "ODMOWA – Karta nie została aktywowana. Aktywuj kartę i spróbuj ponownie.UWAGA: Nie wolno powtarzać obciążeń dla tej karty."
  "82": &82_code "ODMOWA – Nieprawidłowy kod CVV. Sprawdź poprawność wprowadzonych danych i spróbuj ponownie. UWAGA: Nie wolno powtarzać obciążeń dla tej karty.! Może to zostać uznane za próbę oszustwa!"
  "N7": *82_code
  "85": "Bank potwierdził autoryzację."
  # CR: [matik] bardzo ładne korzystanie z anchorów YAMLowych, żeby uniknąć duplikacji!
  "91": &91_code "ODMOWA – Tymczasowy błąd po stronie banku, spróbuj ponownie."
  "92": *91_code
  "94": *91_code
  "98": *91_code
  "B04": &B04_code "ODMOWA - karta utraciła ważność lub jest zablokowana i można jej obciążyć. Użyj innej karty."
  "B14": *B04_code
  "B15": *B04_code
  "B41": *B04_code
  "B43": *B04_code
  "B54": *B04_code
  "E3": "ODMOWA – Błąd systemu ACS w banku. Spróbuj ponownie lub skonsultuj się z bankiem lub sprzedawcą."
  "E4": "ODMOWA – Negatywny wynik weryfikacji 3D-Secure w banku."
  "E5": "ODMOWA – Tymczasowy błąd przy weryfikacji 3D-Secure, spróbuj ponownie później lub skontaktuj się ze sprzedawcą."
